### PR TITLE
Added a Python example to the Stopwatch lesson

### PR DESCRIPTION
**Pull request by M0JPI**
The lesson shows how to control the FPGA fabric using both C and Python.
The shell commands to control the PL fabric clock are included, and a line is added to stop the PLL clock and start it up, to allow for the full use of the clock range.

### CODE REVIEW

**Comment by M0JPI** [comment]
Updated the pull request to correct a spelling mistake (frequency).

**Comment by M0JPI** [comment]
A Python example is added to the Frequency Counter lesson as well as the Stopwatch lesson.

**Comment by Lightsaver7** [comment]
Hey John,
First of all, thank you for updating the knowledge base with the Jupyter/Python version of Stopwatch and Frequency counter (and for the minor code calrifications you did) - we really appreciate it.

I just have one question - What is the reason behind changing the clock frequency in stopwatch.rst to 125 MHz, but leaving it at 
124998750 Hz in the frequency counter? Is it for the frequency counter to be more precise and the stopwatch does not need to be as precise?

Best regards,
Miha Gjura

**Review by Lightsaver7 — APPROVED** [review]

**Review by Lightsaver7 — APPROVED** [review]

**Comment by Lightsaver7** [comment]
Thank you for the explanation.

**Comment by Lightsaver7** [comment]
I will just add some additional commentary to make it simpler for new users to understand what they must do in order to run the Python version

**Pull request merged**
